server:
  port: 8080

spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: perf

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: dev,beans,info
  endpoint:
    health:
      enabled: true
      status:
        order: UP,DOWN,OUT_OF_SERVICE,UNKNOWN

greeting-service:
  greeting: "Ola"
  default-value: "Mundo"